---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: config
  name: config
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    project: piggymetrics
    tier: infrastructure
    app: config
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:    
        project: piggymetrics
        tier: infrastructure
        app: config
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: sqshq/piggymetrics-config
        name: config
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
status: {}
