---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: auth-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: auth-mongodb
    spec:
      containers:
      - image: sqshq/piggymetrics-mongodb
        name: auth-mongodb
        env:
          - name: MONGODB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: piggymetrics
                key: auth_mongodb_password
        ports:
          - containerPort: 27017
        resources: {}
      restartPolicy: Always
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
status: {}
