---
apiVersion: v1
kind: Service
metadata:
  name: account-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: account-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: account-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: account-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: account-mongodb
    spec:
      containers:
      - name: account-mongodb
        env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_mongodb_password
        ports:
          - containerPort: 27017
        image: sqshq/piggymetrics-mongodb
      restartPolicy: Always
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
